### PR TITLE
apply template sync and first completion of pipeline

### PR DESCRIPTION
**Pull request by mashehu**
Okay, this is a bit of messy one, but the two main things are:
* merged the changes from the new template
  * This includes a change in the conda environment => CI test fails until docker hub image is rebuilt (`ModuleNotFoundError: No module named 'pymdownx'`)
* completed the pipeline(?)
  * This depends how far we want to go, but it is currently complete in a sense, that it takes unmapped .fastq files and puts out .bed files with CAGE defined transcription start site clusters

## PR checklist
 - [x] This comment contains a description of changes (with reason)
 - [x] If you've fixed a bug or added code that should be tested, add tests!
 - [x] Ensure the test suite passes (`nextflow run . -profile test,docker`).
 - [x] Make sure your code lints (`nf-core lint .`).

### CODE REVIEW

**Comment by mashehu** [comment]
I added an optional bowtie alignment process, which changed the software requirements, so the tests will fail here until the new docker image is built.

**Comment by apeltzer** [comment]
As its not a released pipeline at all its also fine if you merge this into dev to get the Container built and then continue with a working container I think.

**Comment by mashehu** [comment]
> As its not a released pipeline at all its also fine if you merge this into dev to get the Container built and then continue with a working container I think.

Okay, can then somebody with the right permissions merge?

**Comment by apeltzer** [comment]
✔️ You can then tests properly here using Github Actions & get this shaped for a real first release :-)

**Pull request merged**
