### PR TITLE
Fix tests, switch to github actions, improve software version scraper

### PR DESCRIPTION
**Pull request by mashehu**
- I fixed the tests, so that they work again.
- I added github actions and removed `.travis.yaml`
- I added all currently used software to the scraper
- I updated `nextflow.config` to the current standard

## PR checklist
 - [x] This comment contains a description of changes (with reason)
 - [x] Ensure the test suite passes (`nextflow run . -profile test,docker`).
 - [x] Make sure your code lints (`nf-core lint .`).

### CODE REVIEW

**Comment by MaxUlysse** [comment]
I think you still have an issue with Github Actions as there is currently no checks

**Comment by mashehu** [comment]
> I think you still have an issue with Github Actions as there is currently no checks

Doesn't it need to merge first in order to set them up, because this is the commit introducing them?

**Comment by MaxUlysse** [comment]
I would say no, you don't seems to have any test happening on your own `dev` branch: https://github.com/mashehu/cageseq/actions

**Comment by mashehu** [comment]
I think that's because I was merging into master on my own repo and just created the dev branch after that, which doesn't trigger the actions.

**Comment by MaxUlysse** [comment]
Can you add a random commit to try to trigger the actions?

**Comment by MaxUlysse** [comment]
Ok, so linting works on your own fork, but CI is failing:
https://github.com/mashehu/cageseq/actions/runs/38782337
https://github.com/mashehu/cageseq/runs/443738672?check_suite_focus=true

So you were right about this commit introducing the checks

**Comment by mashehu** [comment]
Good.
Any idea, why the ci test uses the old `nextflow.config`, with the now removed `params.container` inside? Isn't it using the config from the repo?

**Comment by MaxUlysse** [comment]
It's still here; https://github.com/mashehu/cageseq/blob/2d53f538bdb6a3fb929c4b918d7a424519c91c32/conf/base.config#L14

**Comment by MaxUlysse** [comment]
which is included here: https://github.com/mashehu/cageseq/blob/2d53f538bdb6a3fb929c4b918d7a424519c91c32/nextflow.config#L64

**Comment by mashehu** [comment]
I am almost there now, but the CI is still failing: https://github.com/mashehu/cageseq/runs/444004335
I think I am in another chicken-egg problem, where it is failing because it pulls the `nfcore/cageseq:dev` docker image, which will be updated with this commit to contain bowtie 2. The tests runs through locally using the `mashehu/cageseq:dev` docker image.

**Comment by MaxUlysse** [comment]
I see the issue, if it's only the last problem, I'll approve then.
I think the way to circumvent that would be to make a first PR which only update the `environment.yml` file, or to push the newly created container to dockerhub.

**Comment by mashehu** [comment]
Yes, I agree that in hindsight, I should have first updated the Dockerfile and environment.yml before continuing with the CI switch. Sorry for trying to jump-start it 🙂.

**Pull request merged**
